FROM node:22-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci 

COPY . .

ARG NEXT_PUBLIC_API
ARG NEXT_PUBLIC_SOCKET_URL

ENV NEXT_PUBLIC_API=$NEXT_PUBLIC_API
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL

RUN npm run build

FROM node:22-slim AS runtime

COPY --from=builder --chown=node:node /app/.next/standalone ./

COPY --from=builder --chown=node:node /app/.next/static ./.next/static

COPY --from=builder --chown=node:node /app/public ./public

USER node

EXPOSE 3000

CMD ["node", "server.js"]
